apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: inetsoft-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inetsoft
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: inetsoft-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: inetsoft-role
subjects:
  - kind: ServiceAccount
    name: inetsoft
