version: '3'
services:
  postgresql:
    image: 'postgres:12'
    environment:
      POSTGRES_USER: inetsoft
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: inetsoft
      # these arguments are required for PostgreSQL to work with Oak
      POSTGRES_INITDB_ARGS: --lc-collate=C --lc-ctype=C --encoding=UTF8
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres:/var/lib/postgresql/data/pgdata
  init:
    image: 'docker.inetsoft.com/inetsoft/init-oak:13.4.133287'
    depends_on:
      - postgresql
    deploy:
      restart_policy:
        condition: none
    volumes:
      - ./shared:/var/lib/inetsoft/shared
    environment:
      INETSOFT_MASTER_PASSWORD: dontsharethis
      INETSOFT_LICENSE: your_license_key
      INETSOFT_CONFIG_URL: git://https://github.com/my_company/inetsoft-config.git
      INETSOFT_CONFIG_USERNAME: my_git_user
      INETSOFT_CONFIG_PASSWORD: my_git_token
      INETSOFT_DB_TYPE: PostgreSQL
      INETSOFT_DB_URL: jdbc:postgresql://postgresql:5432/inetsoft
      INETSOFT_DB_DRIVER: org.postgresql.Driver
      INETSOFT_DB_USER: inetsoft
      INETSOFT_DB_PASSWORD: secret
  server:
    image: 'docker.inetsoft.com/inetsoft/server:13.4.133287'
    depends_on:
      - init
    volumes:
      - ./shared:/var/lib/inetsoft/shared
    environment:
      INETSOFT_MASTER_PASSWORD: dontsharethis
    ports:
      - '8080:8080'
    entrypoint: [ "/usr/local/inetsoft/bin/wait-for-file.sh", "/var/lib/inetsoft/shared/.config-complete", "/usr/local/inetsoft/bin/start-server.sh" ]
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 2G
  scheduler:
    image: 'docker.inetsoft.com/inetsoft/scheduler:13.4.133287'
    depends_on:
      - init
    volumes:
      - ./shared:/var/lib/inetsoft/shared
    environment:
      INETSOFT_MASTER_PASSWORD: dontsharethis
    entrypoint: [ "/usr/local/inetsoft/bin/wait-for-file.sh", "/var/lib/inetsoft/shared/.config-complete", "/usr/local/inetsoft/bin/start-scheduler.sh" ]
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 1G
