version: '3'
services:
  init:
    image: 'docker.inetsoft.com/inetsoft/init-fs:2021.0.0'
    user: '1000:1000'
    restart: 'no'
    volumes:
      - ./shared:/var/lib/inetsoft/shared
      - ./config:/var/lib/inetsoft/external
    environment:
      INETSOFT_MASTER_PASSWORD: ${INETSOFT_MASTER_PASSWORD:?err}
      INETSOFT_LICENSE: ${INETSOFT_LICENSE:?err}
      INETSOFT_CONFIG_URL: file:///var/lib/inetsoft/external
  server:
    image: 'docker.inetsoft.com/inetsoft/server:2021.0.0'
    user: '1000:1000'
    depends_on:
      - init
    volumes:
      - ./shared:/var/lib/inetsoft/shared
    environment:
      INETSOFT_MASTER_PASSWORD: ${INETSOFT_MASTER_PASSWORD:?err}
    ports:
      - '8080:8080'
    entrypoint: [ "/usr/local/inetsoft/bin/wait-for-file.sh", "/var/lib/inetsoft/shared/.config-complete", "/usr/local/inetsoft/bin/start-server.sh" ]
  scheduler:
    image: 'docker.inetsoft.com/inetsoft/scheduler:2021.0.0'
    user: '1000:1000'
    depends_on:
      - init
    volumes:
      - ./shared:/var/lib/inetsoft/shared
    environment:
      INETSOFT_MASTER_PASSWORD: ${INETSOFT_MASTER_PASSWORD:?err}
    entrypoint: [ "/usr/local/inetsoft/bin/wait-for-file.sh", "/var/lib/inetsoft/shared/.config-complete", "/usr/local/inetsoft/bin/start-scheduler.sh" ]