apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inetsoft-spark-master-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
