apiVersion: v1
kind: Service
metadata:
  name: inetsoft-mysql
  labels:
    app: inetsoft-mysql
spec:
  ports:
    - port: 3306
      protocol: TCP
  clusterIP: None
  selector:
    app: inetsoft-mysql
