apiVersion: apps/v1
kind: Deployment
metadata:
  name: inetsoft-server
  labels:
    app: inetsoft-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inetsoft-server
  template:
    metadata:
      labels:
        app: inetsoft-server
        inetsoftClusterNode: "true"
    spec:
      serviceAccountName: inetsoft
      imagePullSecrets:
        - name: inetsoft-docker-secret
      containers:
        - name: inetsoft-server
          image: docker.inetsoft.com/inetsoft/server:13.4.133301
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "2Gi"
              cpu: "2"
            limits:
              memory: "2Gi"
              cpu: "2"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 180
            periodSeconds: 15
          env:
            - name: INETSOFT_MASTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: inetsoft-master-secret
                  key: password
          volumeMounts:
            - mountPath: "/var/lib/inetsoft/shared"
              name: inetsoft-shared
      initContainers:
        - name: inetsoft-init-server
          image: docker.inetsoft.com/inetsoft/init-oak:13.4.133301
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "2Gi"
              cpu: "2"
          volumeMounts:
            - mountPath: "/var/lib/inetsoft/shared"
              name: inetsoft-shared
      volumes:
        - name: inetsoft-shared
          persistentVolumeClaim:
            claimName: inetsoft-shared-pvc