apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: inetsoft
resources:
  - pvc-shared.yaml
  - rbac.yaml
  - service-server.yaml
  - deployment-server.yaml
  - deployment-scheduler.yaml
