apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inetsoft-shared-pvc
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
