apiVersion: v1
kind: Service
metadata:
  name: inetsoft-server
  labels:
    app: inetsoft-server
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: inetsoft-server
